package server.world.messaging.messages;

/**
 * A message generated by a world or a world entity.
 */
public abstract class WorldMessage {

    /**
     * Get the message type.
     * @return The message type.
     */
    public abstract WorldMessageType getType();
}
