package gaia.server.world.messaging.messages;

/**
 * Represents a message generated by a world or a world entity.
 */
public interface IWorldMessage {

    /**
     * Get the message type.
     * @return The message type.
     */
    WorldMessageType getMessageType();
}
