package gaia.server.world.messaging.messages;

import gaia.server.engine.IWorldEventsHandler;

/**
 * Represents a message generated by a world or a world entity.
 */
public interface IWorldMessage {
	
	/**
	 * Process the world message.
	 * @param handler The handler for world events. 
	 */
	void process(IWorldEventsHandler handler);
}
